name: gestamp_ml
channels:
  - conda-forge
  - pytorch
dependencies:
  - python=3.10
  - pandas
  - numpy
  - matplotlib
  - seaborn
  - scikit-learn
  - smt
  - pytorch
  - torchvision
  - cpuonly
  - pip
  - pip:
    - "pina-mathlab[tutorial]"
